name: Deploy Spring Boot to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Upload JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          source: "build/libs/*.jar"
          target: "/home/ubuntu/app"

      - name: Restart app on EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Stopping existing app..."
            pkill -f 'java -jar' || echo "No running app found"
            sleep 5

            cd /home/ubuntu/app

            JAR_FILE=$(ls -t *.jar | head -n 1)   # pick latest jar
            echo "Starting $JAR_FILE..."
            
            # Start in fully detached mode
            setsid java -jar "$JAR_FILE" --server.port=9090 > app.log 2>&1 < /dev/null &

            sleep 2
            echo "App restarted successfully"
